.TH INFORMANT 1 "22 FEBRUARY 2021" informant-v0.4.2 "Informant Manual"
.SH NAME
informant \- An Arch Linux News reader and pacman hook.

.SH SYNOPSIS
.I informant
[options] check

.I informant
[options] list [--reverse --unread]

.I informant
[options] read [<item> | --all]

.SH DESCRIPTION
.I informant
has three modes of operation: check, list and read.

.SH COMMANDS

.TP
.B check
Check for unread Arch Linux News items and exit with status code equal to the
number of unread items.

.TP
.B list
Print out the headlines of the most recent news items (regardless of whether or
not they have been read). list also can take two options of its own:
.RS
.TP
.B \-\-reverse
Print the headlines oldest to newest (instead of newest to oldest).
.TP
.B \-\-unread
Print the headlines of only unread items.
.RE

.TP
.BR read " " [<item> | --all]
Print the given news item and mark it as read.
.B <item>
can be given as an index (printed by the
.B list
command without the
.B \-\-unread
or
.B \-\-reverse
options) or as a string matching part of the headline of a news item.
.B read
will exit with status code 255 if it does not have permission to write to the
save file.

When run without
.BR <item>
or
.B \-\-all
read will run interactively printing all unread news items from oldest to newest
prompting the user if they want to continue reading.
.RS
.TP
.B \-\-all
Mark all the most recent news items as read without printing them.
.RE

.SH OPTIONS
These are the global options which can be applied to any of the subcommands.

.TP
.BR \-c " " <cfile> ", " \-\-config=<cfile>
Read configuration from <file>. Configuration and syntax can be found below in
CONFIGURATION.

.TP
.BR \-d ", " \-\-debug
Print the command line arguments and don't make changes to the save file, useful
for debugging.

.TP
.BR \-r ", " \-\-raw
When printing items do not replace any markup, items will be printed exactly as
returned by the RSS feed.

.TP
.BR \-f " " <file> ", " \-\-file=<file>
Use <file> as the save location for marking items as read. This is a binary
file.

.B NOTE
Changing the file will not change the file read by the pacman hook because the
pacman hook runs as root, if you want to change that you can do so manually by
editing /usr/share/libalpm/hooks/00-informant.hook

.TP
.BR \-\-no\-cache
Do not check the cache.

.TP
.BR \-h ", " \-\-help
Print the help and exit.

.TP
.BR \-V ", " \-\-version
Print the version information and exit.

.SH CONFIGURATION
Informant can be configured to check multiple feeds instead of just the Arch
Linux News feed (whether having it do so is actually useful or not is left up to
the user). Informant will check for an
.B informantrc.json
file in a few places. It will check in this order:
.RS
.PP
\- CLI provided option (cfile)

.PP
\- $HOME/.informantrc.json

.PP
\- $XDG_CONFIG_HOME/informantrc.json

.PP
\- /etc/informantrc.json

.PP
\- For each directory $d in $XDG_CONFIG_DIRS it will look for $d/informantrc.json
.RE

.PP
.B NOTE
IF you want the configuration file to be used in the pacman hook make sure to
use a save location that will be accessible to informant when running as
root/sudo.

.SS Configuration Syntax
The syntax of informantrc.json is a JSON object containig on key:
.B feeds
that is a list describing the feeds you want informant to check. Each feed is
represented as a JSON object with the following keys:
.RS

.TP
.BR name (optional)
used to show which feed each news item is from

.TP
.BR url (required)
the feed URL

.TP
.BR title-key (optional)
defaults to
.IR title ,
the key used to reference the news item title in the feed

.TP
.BR body-key (optional)
defaults to
.IR summary ,
the key used to reference the news item body in the feed

.TP
.BR timestamp-key (optional)
defaults to
.IR published ,
the key used to reference the news item date in the feed
.RE

.PP
For example, the below informantrc.json will configure informant to check the
Arch Linux News feed as well as the Arch Linux 32 News Feed:
.EX
{
    "feeds": [
        {
            "name": "Arch News",
            "url": "https://archlinux.org/feeds/news",
            "title-key": "title",
            "body-key": "summary",
            "timestamp-key": "published"
        },
        {
            "name": "Arch32 News",
            "url": "https://bbs.archlinux32.org/extern.php?action=feed&fid=12&type=atom",
            "title-key": "title",
            "body-key": "summary",
            "timestamp-key": "updated"
        }
    ]
}
.EE

.SH AUTHOR
Bradford Smith <\fIhttps://github.com/bradford-smith94\fR>

.SH LICENSE
MIT.

.SH BUGS
Please report bugs at:
<\fIhttps://github.com/bradford-smith94/informant/issues\fR>.

.SH "SEE ALSO"
.BR alpm-hooks (5)
